### ISSUE TITLE
Search for delegates username

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#10]
To correspond with: https://github.com/LiskHQ/lisk-ui/issues/8

**Comment by Isabello** [comment]
This looks like it could be easy to do. Would you like me to take this over @karmacoma

**Comment by Isabello** [comment]
Resolved by : https://github.com/LiskHQ/lisk-explorer/commit/1cbcbbe1c99d675324cb8ba1156011ee66ec1a05
