### ISSUE TITLE
Setup unit test environment for frontend code

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#100]
We should setup the necessary environment for running unit tests against the frontend angular code, and include it as part of the travis-based continuous integration process, e.g. using karma, phantomjs, mocha and chai.

**Comment by karmacoma** [comment]
We will need to update our docs: https://github.com/LiskHQ/lisk-explorer#tests to reflect running backend versus frontend tests.

**Comment by jestersimpps** [comment]
i can set this up.

**Comment by Isabello** [comment]
I believe this was already setup as part of the end to end tests
implemented by @slaweet

**Comment by jestersimpps** [comment]
ok, I opened a pr anyway
