### ISSUE TITLE
Improve delegate page: Add direct links

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#110]
Current Behaviour:

When linking to delegate, we are still linking to the address page.

Expected Behaviour:

When linking to delegate, we should link to the delegate page.

How to reproduce:

- Click on a delegate link within Delegate Monitor.
- Click on a delegate link when showing Block.

**Comment by karmacoma** [comment]
Closed by #115

**Comment by 4miners** [comment]
Connected to https://github.com/LiskHQ/lisk-explorer/issues/128

**Comment by karmacoma** [comment]
We will resolve through #128
