### ISSUE TITLE
Get rid of bower

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-explorer#120]
Currently, there are npm dependencies and bower dependencies. Let's merge them together.

Further info in this discussion: 
https://github.com/LiskHQ/lisk-explorer/pull/119#discussion_r108939749

note that some of the bower dependencies (namely sigma and amstockchart) weren't available in bower two years ago, thus there are fetched from lisk-specific repos:
https://github.com/LiskHQ/lisk-explorer/blame/development/bower.json

I checked and all bower dependencies are available in npm, though sometimes not with the same version.

**Comment by alepop** [comment]
Resolved by #153

**Comment by Isabello** [comment]
Closed by @alepop
