### ISSUE TITLE
Breadcrumbs are sometimes empty 

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#121]
Current behavior:
Breadcrumbs are sometimes empty, that happen randomly. When it happens they looks like:
![breadcrumbs](https://cloud.githubusercontent.com/assets/22824146/24593634/be531fe4-1825-11e7-8886-d65c4c6bf4a9.png)

Expected behavior:
Bradcrumbs should be always displayed.

Steps to replicate:
Enter any page then `Ctrl+Shift+R`.

**Comment by alihaghighatkhah** [comment]
Couldn't reproduce this issue. I assume it has been fixed with other changes.

**Comment by 4miners** [comment]
Yep, I also cannot reproduce it anymore.
