### ISSUE TITLE
Project structure improvements

### ISSUE THREAD

**Issue by alihaghighatkhah** [LiskHQ/lisk-explorer#138]
Current state:
 - Filters are entirely in `./src/filter.js` file
 - Some filters seem to perform as directives.
 - Routing configurations are mixed with application  `run` method.

Expected state:
 - Separate filters into modules with dedicated files.
 - Change filters into directives in cases the functionality suggests.
 - Separate routing from `run` method.

**Comment by Isabello** [comment]
Closed via https://github.com/LiskHQ/lisk-explorer/pull/157
