### ISSUE TITLE
networkMonitor page SSL error

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-explorer#14]
When website is visited using https, like here:

https://testnet-explorer.lisk.io/networkMonitor

Both firefox and chrome report certificate error on the networkMonitor page because of "external http" unencrypted content.

**Comment by Gr33nDrag0n69** [comment]
after check the content is the map background loaded from http://*.tile.osm.org/

**Comment by Isabello** [comment]
I just tested a fix for this

We change this line: https://github.com/LiskHQ/lisk-explorer/blob/f253d0315a9f2b5840b6fcfb384f33afacfa1cf6/public/src/js/services/networkMonitor.js#L109
```
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(this.map);
```

These are the HTTPS version of the same information, we change the entries to these
```https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png

https://www.openstreetmap.org/copyright
```

**Comment by Isabello** [comment]
Closed by : https://github.com/LiskHQ/lisk-explorer/commit/2208b63d08b0871eaa7b981488da33b8ddd2ac87
