### ISSUE TITLE
Beautify the Amounts in the transaction List

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-explorer#144]
To improve the clarity I suggest the following:

1. Reduce/round the decimal places to maybe 4. It is sufficient if the detail view of the transaction showns the exact value to 8 decimal places.
2. Also use the same amount of decimal places on round numbers. Example: 20000.0000 LSK
3. Don't center the amount in the green/red field but align the decimal point, or right align with a given right padding.

This way, it's much easier to spot the size of the transactions.

**Comment by SherlockStd** [comment]
Really nice, can I handle it ?
