### ISSUE TITLE
Loading less/more transactions not works

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#146]
Current behavior:
`Less`/`More` button are always disabled, even when there is more txs to load.

Expected behavior:
They should works.

Steps to reproduce:
Enter some address page with bit amount of txs, like `/address/18278674964748191682`.

Fix:
https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/transaction/list.html#L28 and https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/transaction/list.html#L31 should be `!vm.txs.lessData`

**Comment by alepop** [comment]
@4miners Can not reproduce. Button works.

**Comment by 4miners** [comment]
@alepop That bug affect branch `development`.

**Comment by slaweet** [comment]
Less/More buttons work in `development` branch, must have been fixed in the meantime
