### ISSUE TITLE
Background missing for txs sent to self

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#147]
Current behavior:
Missing background when for transactions sent to self.

Expected behavior:
Background for those transactions should be gray.

Steps to reproduce:
Enter address page which contains such txs, like `/address/16010222169256538112L`, there is tx `9878813660430018227` which is affected by this bug.

Fix:
https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/transaction/tx.html#L13 should be `'txvalues-default': tx.type != 0 || $parent.vm.address.address === undefined || tx.senderId == tx.recipientId`

**Comment by alepop** [comment]
@4miners Can not reproduce. The background color is the same as for other transactions.

**Comment by 4miners** [comment]
@alepop That bug affect branch `development`.
