### ISSUE TITLE
Previous page not works on blocks

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#148]
Current behavior:
When click on `Previous page` button nothing happens.

Expected behavior:
When click on `Previous page` button - previous blocks should be displayed.

Steps to reproduce:
Eneter `/blocks/` page and click `Previous page` button.

Fix:
https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/blocks.html#L37
`pagination.previousPage` and `pagination.nextPage` should be `vm.pagination...`

**Comment by alepop** [comment]
@4miners I can not reproduce this behavior on https://explorer.lisk.io/. Maybe somebody already fixes this bug.

**Comment by 4miners** [comment]
@alepop That bug affect branch `development`, official explorer is running previous version.

**Comment by slaweet** [comment]
This was fixed in https://github.com/LiskHQ/lisk-explorer/pull/158. I just checked and it works. Closing.
