### ISSUE TITLE
Use webpack bundling 

### ISSUE THREAD

**Issue by alihaghighatkhah** [LiskHQ/lisk-explorer#153]
**Current behaviour:**
We're using Grunt task runner for concatenating JavaScript files and handling dependency bindings manually.

**Expected behaviour:**
Preferred is using Webpack bundler as it already provides options for minification and sourcemaps for your bundle, runs as middleware through a custom server called webpack-dev-server, which supports both live reloading, can also add ES6 to ES5 transpilation, and CSS pre- and post-processors and many other advantages.

**Comment by alepop** [comment]
@alihaghighatkhah can you assign this issue to me? I want to do this together with #105

**Comment by Isabello** [comment]
Closed via #159
