### ISSUE TITLE
Breadcrumbs are always empty

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#177]
### Expected behaviour

Breadcrumbs should be populated.

### Actual behaviour

Breadcrumbs are empty. See pale grey rectangle below top navigation bar.

![finder finder today at 18 16 43](https://cloud.githubusercontent.com/assets/8068/26593439/55ac5214-4564-11e7-8e8d-01beb5cb43b1.png)

### Steps to reproduce

Open the explorer on any page.

**Comment by karmacoma** [comment]
Maybe we should just remove breadcrumbs entirely. Not sure if actually needed.

**Comment by 4miners** [comment]
I like them, it's usefull feature - we should keep it.

**Comment by alihaghighatkhah** [comment]
It's interesting, they're working for me. I tried them non 2 versions of OSX and ubuntu. maybe give us a bit more details about how to reproduce it.

**Comment by karmacoma** [comment]
@alihaghighatkhah: Browser used was Safari `10.1.1`.

**Comment by 4miners** [comment]
@alihaghighatkhah I have same issue running explorer from current `development` branch, both on Firefox and Chrome.

**Comment by alepop** [comment]
@alihaghighatkhah @karmacoma @4miners if you run `npm start` and `node app.js` then breadcrumbs will be displayed. But if you run `npm rub build` and `node app.js` then you will not see the breadcrumbs. And in console you can see the error.
![Screen Shot 2017-06-01 at 16.47.09](http://static.gitscout.com/81b3bc7eb1c436f50e6c8172f6ccafecd6c8928f030606307703303923d703f4.png)

**Comment by alepop** [comment]
After some research, I found that the error was caused by `-p` (production) flag especially with `-optimize-minimize` flag included in a production build. Some explanation here https://stackoverflow.com/questions/30322921/webpack-optimize-with-uglifyjs-plugin-causes-runtime-error

**Comment by reyraa** [comment]
Good job @alepop . This fixed the issue. thanks
