### ISSUE TITLE
Explorer should also display address not yet used in blockchain

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-explorer#193]
### Expected behaviour
Explorer should also display account not yet used in blockchain with balance of 0 or/and information that this account has not been claimed/received any funds yet.

### Actual behaviour
Nothing does happen. It just reloads to main page.

### Steps to reproduce
Search for non existing address.

**Comment by Isabello** [comment]
It would display nothing. Better to display a better message that the
account is not found than load the accounts page with a bunch of null data

**Comment by MichalTuleja** [comment]
No need to implement that feature.
