### ISSUE TITLE
Network Monitor: OS X 10.11.4 is not detected correctly under platforms

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#2]
Courtesy of densmirnov on lisk.chat:

> When you run a node build from source on os\x (10.11.4) it appears on Network Monitor with correct icon, but doesn't listed under 'platforms'. It shows '1 connected peers running on other platforms' instead.

**Comment by Isabello** [comment]
closed by https://github.com/LiskHQ/lisk-explorer/commit/f253d0315a9f2b5840b6fcfb384f33afacfa1cf6
