### ISSUE TITLE
Displays only 0.5.0

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-explorer#22]
https://explorer.lisk.io/networkMonitor

Displays only 0.5.0 while i can clearly see in logs on my nodes that other version still exists on network.

**Comment by Isabello** [comment]
This is a non issue.

**Comment by karek314** [comment]
It's incorrect anyway, there are other nodes version than 0.5.0, im aware nodes below 0.5.0 are dropped but network monitor result is wrong. 

Is current count only 0.5.0 or all including old ones ? How much are not updated yet ?

**Comment by 4miners** [comment]
Network monitor shows peers that are in network (or was lately and now are disconnected). Since all nodes with version lower than 0.5.0 are rejected by network - they are no longer a part of it. Such behavior is correct.

**Comment by karek314** [comment]
Nodes below 0.5.0 are still part of network, but cannot participate due protocol changes in latest version. It's network monitor, it should display all nodes from beginning, possibly marking those incompatible with current network protocol as harmful/useless or whatever. Monitor goal is to actually monitor network, see adoption of new releases including those which will remove support for previous versions. This is my understanding of this and i believe it's correct, most Bitcoin monitors keep it this way as well.

**Comment by Isabello** [comment]
Nodes below 0.5.0 are not part of the network. they cannot communicate with any peers on 0.5.x or above. There is nothing gained by monitoring these peers.

**Comment by Isabello** [comment]
This part of the code here is why this is a wontfix.

https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L557

**Comment by karek314** [comment]
Im aware that nodes below 0.5.0 are removed, but explorer is for statistics as well, currently we can't know how many old versions is still running. that's all I'm saying.

**Comment by 4miners** [comment]
Statistics about peers running older incompatible versions are simply not available in core, so explorer doesn't have a source to pull from. Imo tracking for those should not be added because of work amount compared to possible benefit gain. Also core should be efficient so littering it with unnecessary data doesn't make sense.

If anyone need those statistics - it's possible to get them by connecting explorer to old version node.

**Comment by Isabello** [comment]
I would say this is definitely closed now. You can log this issue with core but I don't see us changing the way EVERSION works.
