### ISSUE TITLE
Implement sorting on transactions list

### ISSUE THREAD

**Issue by E1337Lisk** [LiskHQ/lisk-explorer#225]
Hello!!!

I was looking on my account on https://explorer.lisk.io and I was thinking of a small detail that will make it even more user friendly. As I was looking for a transaction I tried to click on sender to sort them and find  it but you can not do this yet.

So would it be a idea to make : Transaction ID/Date/Sender/Recipient/Amount/Fee/Confirmations clickable?

So that you can have senders for example in alphabet and amount of the transaction from high to low and other way around. I don't know if someone else already posted about this but might be nice little detail to add in the future.

E1337
![make clickable](https://user-images.githubusercontent.com/30056340/28037514-e1a2f9c2-65bb-11e7-8956-3346d03b25a9.jpg)

**Comment by 4miners** [comment]
Connected with: https://github.com/LiskHQ/lisk-explorer/issues/150
