### ISSUE TITLE
Add account name for this top account

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-explorer#245]
Please add a hard-coded name for this account: https://explorer.lisk.io/address/3040783849904107057L

It belongs to Coincheck.com (asian exchanger)

This withdrawal was made at Coincheck and went directly from their account on the persons account, from whom I got this proof:
![default](https://user-images.githubusercontent.com/19614645/28935648-88dfa4b6-7885-11e7-8ee9-4b721328b03f.jpg)

**Comment by reyraa** [comment]
Closed by #277
