### ISSUE TITLE
Incoming transaction count on address summary shows wrong total

### ISSUE THREAD

**Issue by desjob** [LiskHQ/lisk-explorer#250]
### Expected behaviour
3 incoming transactions shown
### Actual behaviour
6 incoming transactions shown  (amount of incoming + outgoing transactions?)

### Steps to reproduce
1. create a new address X
2. make 3 transations TO address X
3. cast 3 votes FROM address X

example:
https://explorer.lisk.io/address/8882966637680404533L

**Comment by desjob** [comment]
looks like its related to the delegate votes. I suspect that 1 delegate vote is being counted as both 1 incoming and 1 outgoing transation

**Comment by reyraa** [comment]
This seems to be fixed by #234
