### ISSUE TITLE
Russian Rouble Symbol (₽) Support

### ISSUE THREAD

**Issue by densmirnov** [LiskHQ/lisk-explorer#257]
It's great, that Lisk Explorer supports russian rouble now, but why not use [official unicode symbol for it](https://unicode-table.com/en/20BD/) (_₽_) in interface?

**Comment by alepop** [comment]
Other currencies do not use they symbols too. This feature needs to be implemented for all other currencies.

**Comment by reyraa** [comment]
For the sake of readability, we don't intend to support currency symbols in current design.
