### ISSUE TITLE
Refactor delegate page to update more frequently

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-explorer#27]
In the current implementation there is a lag between block reciept and updating the forger on the delegate list. We need to adjust the method this page will be updated by to update more frequently to keep data as realtime as possible.

**Comment by 4miners** [comment]
Fixed with https://github.com/LiskHQ/lisk-explorer/pull/28/commits/d55cf9b4b1b6f5492381ab1489cd7ed02313296e
