### ISSUE TITLE
Create granular log levels for explorer logging

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-explorer#29]
Currently there is no granular functions for logging in explorer. In order to make production code more efficient we should have the ability to suppress most log functions using logLevel.

Many functions that log currently are mostly for debug purposes, so moving them to debug will provide a small efficiency improvement.

**Comment by Isabello** [comment]
assigned to @5an1ty

**Comment by 5an1ty** [comment]
Should be fixed by: https://github.com/LiskHQ/lisk-explorer/pull/203
