### ISSUE TITLE
Network Monitor: Any version number can be shown in Network Monitor

### ISSUE THREAD

**Issue by densmirnov** [LiskHQ/lisk-explorer#3]
Seems like there is no additional checking for version number, so Network Monitor will display any number entered in config.json

![2016-04-03 13 10 43](https://cloud.githubusercontent.com/assets/811885/14231911/add276b2-f99d-11e5-8758-55d4eb502374.png)

**Comment by fix** [comment]
i would not fix it, since it shows more an issue on lisk core. There should be a way to discover if a node is "legit".

**Comment by karmacoma** [comment]
Lisk `0.5.0` now validates version numbers are semantically correct. "Legit" version numbers need to be determined in Lisk core. Closing.
