### ISSUE TITLE
Change way of tracking statuses on delegate monitor

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#31]
Currently we track delegate statuses on delegate monitor page per round (current and last). That logic can lead to misleading statuses when round is extended one. For example when in network only few of 101 delegates are forging - single round can take few hours to complete. Then one delegate can forge and miss more than 1 block in that round.

That logic should be changed and statuses should be tracked per slots - last 101 slots - green, last 202 slots - semi-green, etc. We will require changes in core to fully achieve that.

**Comment by 4miners** [comment]
We will rethink that after core `1.0.0` release.

**Comment by MichalTuleja** [comment]
After the discussion with @4miners, a decision was made to put the feature on hold. 
It is not planned to be implemented in Lisk Desktop either.
