### ISSUE TITLE
Jenkins workspaces can get deleted even if a run is not successful

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk-explorer#318]
### Expected behaviour

Workspaces should not be deleted if the run does not succeed.

### Actual behaviour

Workspaces get deleted if the run does not succeed.

**Comment by MichalTuleja** [comment]
@Nazgolze @fchavant Is that problem already solved?

**Comment by fchavant** [comment]
@MichalTuleja it is in `1.5.0`

**Comment by MichalTuleja** [comment]
Solved in #486
