### ISSUE TITLE
Add Coincheck and Iconomi to known addresses

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-explorer#330]
Add the main wallet of Coincheck and Iconomi to known addresses:

`3040783849904107057L` : Coincheck.com
`6300322192409448238L`: Iconomi ICO

**Comment by alepop** [comment]
I thought that it was merged already https://github.com/LiskHQ/lisk-explorer/pull/277

**Comment by reyraa** [comment]
@alepop Yes, you're right. unfortunately it's merged into 2.0.0 and I didn't find it.

**Comment by reyraa** [comment]
Closed by #331
