### ISSUE TITLE
Improve version sorting in networkMonitor

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-explorer#335]
### Expected behaviour
Custom sort function in network monitor:
 - should have I/O documentation.
 - can be syntactically tweaked for more readability.

### Actual behaviour
 - There's no documentation
 - We've used too many if conditions

**Comment by Isabello** [comment]
Use natural sort instead maybe. We alreadt use that library for delegates
page

**Comment by reyraa** [comment]
Closed by #336
