### ISSUE TITLE
Fix alignment of headings in header

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-explorer#357]
### Expected behaviour
 Logo should align with breadcrumb, net status info and all the other details in the page.

### Actual behaviour
The Logo has different left margin from that of breadcrumb and also with transaction items in transaction page.

### Steps to reproduce
![screen shot 2017-11-13 at 17 26 28](https://user-images.githubusercontent.com/666685/32736506-ed673054-c897-11e7-8d75-0259318cf5e7.png)

**Comment by karmacoma** [comment]
Closed by PR: https://github.com/LiskHQ/lisk-explorer/pull/358
