### ISSUE TITLE
Search doesnt work?

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-explorer#359]
When I do a search with sender+receiver I don't get the correct result
![searchissue](https://user-images.githubusercontent.com/20902562/32778234-70b8a34c-c939-11e7-9b39-15bdc02dc6c9.png)

**Comment by Joo5t** [comment]
Also, this seems to be an issue or Im mistaken about the search bar being always a global search bar. 
![searchissue2](https://user-images.githubusercontent.com/20902562/32778325-c43d5c9c-c939-11e7-90d7-976802729a24.png)

**Comment by reyraa** [comment]
@Joo5t It works as expected:
 - If the queried address belongs to a delegate, we'll show delegate name in results, this is what happened to _leon_ and _joo5ty_, you searched their address and you got the results with their username. May be a tooltip to show their address in the event of mouse hover would be helpful.
 - If you search for a `senderId=N` and `receiverId=M`, it shows the transactions whose:
   - SenderId is equal to `N` and receiver can be anything
   - ReceiverId is equal to `M` and senderId can be anything

We are aware that this is not the best behaviour and there's a ticket for it: #256 . We'll fix it in near future.
