### ISSUE TITLE
Display status and uptime on mobile devices.

### ISSUE THREAD

**Issue by slasheks** [LiskHQ/lisk-explorer#4]
It would be helpful to have the mobile "shrunk" version of the explorer to display status and uptime. Or perhaps allow the request full version from mobile. Tested: Chrome on Android.

![mobile explorer](https://cloud.githubusercontent.com/assets/6961817/14405510/494c75c4-fe5e-11e5-8a60-0283f377ecb5.png)

**Comment by Isabello** [comment]
You can overcome this by using Request Desktop Site of your mobile browser.

This should be `wont fix` unless we want to create a mobile version of explorer

**Comment by slasheks** [comment]
At the time, the explorer was not displaying the desktop version when requesting from mobile, now it is. A mobile version is not needed, just need to choose what is displayed on lower res.

**Comment by Gr33nDrag0n69** [comment]
@slasheks now that your pull request was merged. Should you close the issue ?

Talking about https://github.com/LiskHQ/lisk-explorer/pull/19
