### ISSUE TITLE
Search for publicKey within explorer

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk-explorer#41]
From here: https://github.com/LiskHQ/lisk-explorer/issues/26

We need to implement publicKeys into the search chain to give users the most options for linking accounts to their identifies on explorer.

This issue is on hold until publickey searching for accounts is implemented in core.

**Comment by 4miners** [comment]
We can now search by public key (https://github.com/LiskHQ/lisk/pull/357), so removing `suspended`.
