### ISSUE TITLE
Build candles during docker deployment

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk-explorer#411]
### Expected behaviour

`grunt candles:build` must be run after an upgrade, not during the build.
The documentation must be updated accordingly.

### Actual behaviour

- candles are being generated at build time, which does not make sense
- the documentation is unclear about when to build candles
  - cached candles in redis might also need to be dropped

### Steps to reproduce

N/A

**Comment by MichalTuleja** [comment]
@fchavant: I've pushed my changes to the README into the branch 411-candles-build-docker-deployment. Could you please update the Dockerfile accordingly?
