### ISSUE TITLE
Network monitor will indicate how many peers are disconnected from the network.

### ISSUE THREAD

**Issue by yairlisk** [LiskHQ/lisk-explorer#417]
When running tests i could see that network monitor will not indicate "disconnected" nodes at all.
it will always take the number of **connected** nodes as the actual number of nodes.

### Expected behaviour
in a case of 1 disconnected node from 20 i would expect to see the following data:
connected peers: 19/20
disconnected : 1 
### Actual behaviour
in a case of 1 disconnected node from 20 user will get the following information:
connected peers: 19/19
disconnected : 0

### Steps to reproduce
start a network with x nodes connected to a network with lisk-explorer.
disconnect one node and check - network monitor.

**Comment by MichalTuleja** [comment]
After a peer gets disconnected the information about it is no longer available. One solution might use a temporary cache that stores all peers and a backend part that tracks current peers. It is still under discussion whether such a functionality is really needed and should be maintained in future releases.

**Comment by karmacoma** [comment]
I would say we remove the reporting of "Disconnected" peers from the Network Monitor and only indicate and list "Connected" peers.
