### ISSUE TITLE
Poloniex candles are missing data

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-explorer#425]
### Expected behaviour
https://explorer.lisk.io/api/exchanges/getCandles?e=poloniex&d=hour

should return data for each hour.

### Actual behaviour
https://explorer.lisk.io/api/exchanges/getCandles?e=poloniex&d=hour

returns data that ends with
```
{
"timestamp": 1518498000,
"date": "2018-02-13T05:00:00.000Z",
"high": "0.00315773",
"low": "0.00314747",
"open": "0.00314752",
"close": "0.00315773",
"liskVolume": "49.23464746",
"btcVolume": "0.15527021",
"firstTrade": 5295425,
"lastTrade": 5295445,
"nextEnd": 1518501545,
"numTrades": 21
},
{
"timestamp": 1518508800,
"date": "2018-02-13T08:00:00.000Z",
"high": "0.00315293",
"low": "0.00315293",
"open": "0.00315293",
"close": "0.00315293",
"liskVolume": "2.10831553",
"btcVolume": "0.00664737",
"firstTrade": 5295885,
"lastTrade": 5295885,
"nextEnd": 1518512379,
"numTrades": 1
},
{
"timestamp": 1518519600,
"date": "2018-02-13T11:00:00.000Z",
"high": "0.00319797",
"low": "0.00318839",
"open": "0.00319700",
"close": "0.00318839",
"liskVolume": "97.03797621",
"btcVolume": "0.31021105",
"firstTrade": 5296569,
"lastTrade": 5296573,
"nextEnd": 1518523154,
"numTrades": 5
},
{
"timestamp": 1518523200,
"date": "2018-02-13T12:00:00.000Z",
"high": "0.00315865",
"low": "0.00315865",
"open": "0.00315865",
"close": "0.00315865",
"liskVolume": "10.05668722",
"btcVolume": "0.03176556",
"firstTrade": 5296980,
"lastTrade": 5296980,
"nextEnd": 1518526781,
"numTrades": 1
},
{
"timestamp": 1518534000,
"date": "2018-02-13T15:00:00.000Z",
"high": "0.00316974",
"low": "0.00316973",
"open": "0.00316974",
"close": "0.00316973",
"liskVolume": "10.74323123",
"btcVolume": "0.03405319",
"firstTrade": 5297368,
"lastTrade": 5297370,
"nextEnd": 1518537549,
"numTrades": 3
}
]
}
```
the `date` param time values are `05`, `08`, 11`, `12`, `15`.

Also visible in the UI
![screen shot 2018-02-13 at 17 23 36](https://user-images.githubusercontent.com/1254342/36160929-bab4e514-10e2-11e8-9c49-f7815a16587c.png)

### Steps to reproduce
Go to 
https://explorer.lisk.io/api/exchanges/getCandles?e=poloniex&d=hour

**Comment by karmacoma** [comment]
Please investigate @MichalTuleja

**Comment by MichalTuleja** [comment]
I've checked data provided by the backend, there are gaps visible in the hours' candle data for Poloniex. The bug is very hard to reproduce, it seems that rebuilding database from scratch makes the data always correct, but using update procedure can lead to gaps. Also, the data may be not available when there are no transactions. Both cases should be solved on the backend side.
