### ISSUE TITLE
Update design to reflect the new Lisk identity

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-explorer#442]
### Expected appearance

The logo, fonts, and colours should follow the new style guidelines introduced by the Lisk relaunch.

### Actual appearance

The logo, fonts, and colours represent the old Lisk identity.

### Steps to reproduce

Open: https://explorer.lisk.io/

### Note

As the explorer will eventually be discontinued by the functionality contained with the Lisk Hub, the design modifications need only be minimal enough to align with the new identity, nothing much more than that.

**Comment by reyraa** [comment]
The bellow list needs to change according to new design guide. I try to keep the changes limited to the styles rules we have already implemented in Explorer, and not inherited from Bootstrap:
 - Logo image asset
 - header background color
 - body font size
 - content and headings font family
 - content and headings font color
 - Alternative grayscale background colors and borders of lists
 - Search box
 - Color pallet of delegate statistic boxes
 - Color pallet of market watcher graph
