### ISSUE TITLE
Subscribe on account/network changes

### ISSUE THREAD

**Issue by stasbar** [LiskHQ/lisk-explorer#454]
Hello,
I'm not sure if it's proper place to ask this kind of question, but I couldn't find better. 
Is it possible to subscribe on account changes or just new transactions/blocks in the network with Lisk client ?
Something like this on ethereum web3js http://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html

**Comment by MichalTuleja** [comment]
Hi stasbar,

Thank you for your question.

Yes, there is such a possibility. Although it is not documented yet, the official clients (Lisk Nano and Lisk Hub) use a similar technique to keep wallet status up to date.

Below an example from Lisk Nano:
```
const openConnection = (state) => {
  const ssl = state.peers.data.options.ssl;
  const protocol = ssl ? 'https' : 'http';

  return io.connect(`${protocol}://${state.peers.data.currentPeer}:${state.peers.data.port}`);
};

connection = openConnection(store.getState());
connection.on('blocks/change', (block) => { (...) });
```

Note that with this API, notifications will be sent on any change to blocks/transactions system. Which means that you would have to filter them per account.

Following events are supported in the current stable version:
`dapps/change, multisignatures/change, delegates/fork, rounds/change, signature/change, transactions/change, blocks/change, multisignatures/signature/change, multisignatures/signature/change, multisignatures/change, delegates/fork, loader/sync`

You can see an example implementation in our repository:
https://github.com/LiskHQ/lisk-nano/blob/v1.3.4/src/store/middlewares/socket.js

If you have any additional questions about this topic, you can ask them here.
