### ISSUE TITLE
Jenkins: Test config should contain certain params for Explorer >= 1.5.0

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#486]
The current Jenkins test environment for Lisk Core is not based on Docker.
The following steps have to be done in order to keep functional tests passing.

- [ ] Lisk Core should be run in Docker environment on Jenkins server using version `0.9.12a`
- [ ] Lisk Core `config.json` should contain `"topAccounts": true`
- [ ] Lisk Core `config.json` should contain `"nethash": "da3ed6a45429278bac2666961289ca17ad86595d33b31037615d4b8e8f158bba"`
- [ ] Lisk Core Postgres database should be restored from Explorer specific blockchain snapshot

This ticket covers support for Jenkins test with Explorer branch 1.5.0, and also 2.0.0.

**Comment by fchavant** [comment]
I do not think changing the `nethash` is necessary as the core is standalone.

**Comment by MichalTuleja** [comment]
The updated Jenkinsfile may be easily applied to the 2.0.0 branch.

**Comment by fchavant** [comment]
@MichalTuleja that's been done already: https://github.com/LiskHQ/lisk-explorer/pull/438/commits/81ed4b872fe0f30f7c15368b18d40671fea7412c
