### ISSUE TITLE
Delegate Monitor Improvement/API - Adding Timeframe

### ISSUE THREAD

**Issue by mrv777** [LiskHQ/lisk-explorer#5]
It would be great if the site: https://explorer.lisk.io/delegateMonitor could have the option to pick the timeframe to see the data for, specifically the productivity, or the API could have a call to get data based on a range.

Example:

Can see the delegates productivity for the last 7 days, last 30 days, lifetime on that site
or if you could input a block range to the API: /api/delegates?from=490000&to=495000

Thanks!

**Comment by fix** [comment]
closing as duplicate of #57

Basically this is imho not the job of a node securing the network, but more of some third parties app to explore the blockchain.

**Comment by fix** [comment]
OK well not closing it finally, since lisk-explorer is a third part app

**Comment by Isabello** [comment]
This will be made possible with this pull request to core.

https://github.com/LiskHQ/lisk/pull/343
