### ISSUE TITLE
Move delegates-specific features out of address pages

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#50]
Because more and more features for delegates is implemented - address pages bacame overloaded with delegate-specific ones. We have various options here, for example:
- create separate page for delegate overview add there some buttons/links that will redirect to another pages (1 feature per page)

Any other ideas?

**Comment by SherlockStd** [comment]
It seems pretty simple, can I handle that ? :smiley:

**Comment by 4miners** [comment]
This is a complex issue. We have to take user experience into account (for example: ease of use, intuitiveness, appearance, etc.). No coding needed at this level. First we need to determine how it should works like, look like, etc. - do you have any ideas?

**Comment by SherlockStd** [comment]
@4miners your idea seems good

**Comment by SherlockStd** [comment]
We leave Adress, Summary and Transactions on the page /address, and we moves the Delegate, Votes and Voters to /delegate ?

**Comment by stellardynamic** [comment]
Perhaps we could use a collapsed/expandable table that displays the most relevant delegate info and/or also make the delegate name a hyperlink to the actual delegate page.

**Comment by stellardynamic** [comment]
If we remove the delegate table we must at least include the delegate name somewhere in address.html as a link to such page. We could also collapse the Delegate detail table like the Votes and Voters sections are collapsed. It would be interesting if there was a detail page for each data item in the table but I'm not sure if that's in the scope of the official explorer.
