### ISSUE TITLE
Docker Compose crash

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk-explorer#504]
### Expected behavior
Running `docker-compose up` should start the application

### Actual behavior
The application crashes as soon as it starts

### Steps to reproduce
Set the image to `lisk/explorer:2.0.0-alpha.1` on docker-compose.yml file.
Run `docker-compose up` and observe the log.

**Comment by MichalTuleja** [comment]
It was a good idea to unify the main config with the docker config there. These params can be also overridden in the VS Code run-time config. No need to manually change the configs to run a local instance. 👍
