### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk-explorer#51]
Breadcrumbs look like good idea here.

**Comment by stellardynamic** [comment]
With Breadcrumbs you would be adding an additional menu correct? Do you have any ideas how it will look and work?

**Comment by 4miners** [comment]
It's navigation component, not really a menu. http://v4-alpha.getbootstrap.com/components/breadcrumb/
Should looks like:
![bread](https://cloud.githubusercontent.com/assets/22824146/21910467/6c10d84a-d91c-11e6-9147-28c56ad03e45.png)

**Comment by stellardynamic** [comment]
This will be especially useful if #50 is expanded upon.
