### ISSUE TITLE
"Next forgers" block incorrect

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk-explorer#520]
### Expected behavior

The list in the "next forgers" block shows the list of upcoming forgers.
Since delegates are shuffled between rounds, only the order of the current round can be known.
Near the end of a round, the list should get smaller such that only "next forgers" of the current round are shown.

### Actual behavior

* Beginning or middle of a round: everything works as expected
* End of a round: list contains forgers, which exceed the current round. Those extra forgers will be shuffled to a different position instead of forge

### Steps to reproduce

**Possibility 1:**

Check those 4 consecutive screenshots. In 1, 2, 3 you see that the old next forger becomes the new "Last block by". But then, the next forger from 3 (hitobb_testnet) did not forge in screen 4. The list is entirely shuffled between 3 and 4.

1. ![996](https://user-images.githubusercontent.com/2603011/38334533-e2e6d754-385b-11e8-8a5f-52ac4ac55daf.png)
2. ![997](https://user-images.githubusercontent.com/2603011/38334546-eb8a8202-385b-11e8-85c6-db2d2eab0e09.png)
3. ![998](https://user-images.githubusercontent.com/2603011/38334563-f0a2fd00-385b-11e8-96f5-2d59e7b5c7dc.png)
4. ![999](https://user-images.githubusercontent.com/2603011/38334571-f8226ffc-385b-11e8-8d02-f5016d5d2917.png)

**Possibility 2:**

Use http://lisk.prolina.org/reboot-counter/ to get a rough idea how much of the current round is left and observe a Lisk Explorer at the point of round change.

### Implementation remarks

While Lisk Explorer tool is affected and can be fixed using some not-so-trivial math, I think the core issue lies in an incorrect implementation of the API endpoint `delegates/getNextForgers?limit=101`. Right now this endpoint always returns 101 results. But every entry behind the current round is incorrect. I'd prefer to see this API only return forgers of the current round.

**Comment by MichalTuleja** [comment]
Thank you for the bug report @webmaster128.
It is about to be fixed in the following patch release.

**Comment by MichalTuleja** [comment]
The following solution has to be applied:
1. Get current height from core `/api/blocks/getHeight` -> `{height: "1234"}`
1. Calculate remaining rounds `101 - ((current_height - 1) mod 101)`
1. Result of the calculation is the limit in the request  `/api/delegates/getNextForgers?limit=101` -> `{delegates: [ (...) ]}`
