### ISSUE TITLE
Add a filter menu to view specific type of transactions

### ISSUE THREAD

**Issue by redsn0w0** [LiskHQ/lisk-explorer#57]
Hi,

I would like to see a little filter menu (positioned in the right side of the page) with the possibility to choose to view only specific type of Tx.  

Like the one of the bitcoin block explorer (https://blockchain.info) but only with: sent, received & delegate vote (maybe also second signature creation) Tx.

Tx = transaction

Is this possible? Because I think it would be really useful.

Thanks for the attention.

**Comment by SherlockStd** [comment]
Yep I think this is possible we need confirmation from @4miners but technically yes :smile: 
Someone need to work on that I agree with you :+1:

**Comment by 4miners** [comment]
@redsn0w0 Good idea, I will schedule that.
@SherlockStd There is no proper core endpoint to get that now, so please hold for now.

**Comment by SherlockStd** [comment]
@4miners I was thinking to do that only on frontend ... Get all transactions then display only a particular type of transaction :/ isn't possible ?

**Comment by 4miners** [comment]
It's possible but costly - because you need to call transactions API multiple times and then filter out not needed txs - it's not optimal. So suspend until https://github.com/LiskHQ/lisk/issues/380 is resolved.

**Comment by redsn0w0** [comment]
@4miners I think it will be also useful to add _total lisk received_ (like on blockchain.info) and remember to add the color green & red to the little arrows (number of transactions in/out, check down below).


![schermata 2017-01-26 alle 18 43 59](https://cloud.githubusercontent.com/assets/14859148/22343221/8e7928d4-e3f7-11e6-8ca5-7147c359557f.png)

**Comment by 4miners** [comment]
@redsn0w0 can you open new issue for that?

**Comment by redsn0w0** [comment]
Done @4miners #77

**Comment by 4miners** [comment]
Endpoint is already available on core dev version and will be also on testnet soon - so removing `suspended` label.

**Comment by redsn0w0** [comment]
Is it also possible to add "_Total received_" & "_Total sent_" ?

**Comment by 4miners** [comment]
@redsn0w0 Sure.

**Comment by 4miners** [comment]
I divided that issue into 2 separate ones: https://github.com/LiskHQ/lisk-explorer/issues/149 https://github.com/LiskHQ/lisk-explorer/issues/150
