### ISSUE TITLE
12 Character+ balance pushes Navigation box and LSK off page on mobile

### ISSUE THREAD

**Issue by stellardynamic** [LiskHQ/lisk-explorer#58]
**As you can see this very long balance extends the page in a unwanted manner. The Navigation has nearly disappeared and LSK and the last number cannot be seen. 3 char shorter and the clipping is still an issue.

![offpagemobilenav](https://cloud.githubusercontent.com/assets/7875147/21871525/504392a0-d828-11e6-8717-753d7b4da40b.png)

**Comment by 4miners** [comment]
That is valid issue, reopened.

**Comment by stellardynamic** [comment]
This pull request should fix/close this issue
https://github.com/LiskHQ/lisk-explorer/pull/71
