### ISSUE TITLE
Prevent a test node from forging

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#586]
Some e2e tests are failing when the forging is enabled. To keep the test blockchain at the same height for longer the forging should be disabled in the test node config.

**Comment by lsilvs** [comment]
@MichalTuleja I believe this is related to version 2.x only

**Comment by MichalTuleja** [comment]
The height of the test blockchain does not increase when running.
The branch `2.x` should be also checked.

**Comment by MichalTuleja** [comment]
The branch `2.x` is also fine.
The last fix to the e2e script was applied in commit `8aaac79e6f161366c4205bfdb1d2553d273c9050`.
