### ISSUE TITLE
The known.json file should be independent from the release cycle

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#601]
### Expected behavior
The `known.json` file contains particular accounts that are important to the Lisk ecosystem.
Due to the fact that they change more frequently than the regular code changes are applied in mainnet, the source of this data must not come from the same repository.

### Actual behavior
Currently all non-delegate account names are stored in the `known.json` file place in the root directory of the `lisk-explorer` project. This file is mostly dependent on the release cycle.

**Comment by lsilvs** [comment]
Have in mind the currently `known.json` addresses are stored in Redis when the application starts.
