### ISSUE TITLE
Columns mixed up

### ISSUE THREAD

**Issue by shilch** [LiskHQ/lisk-explorer#612]
If the transaction page has a width of 1200px or more the columns in the "Details" section are mixed up. The following is a screenshot of https://explorer.lisk.io/tx/17719168675260317171.  
This seems to be the case for every transaction page.  

![screenshot](https://user-images.githubusercontent.com/11890358/39573163-5b2ea4b2-4ed2-11e8-9791-41f2fa334fdc.png)

Note: Binance is not the sender but the receiver here. So the two address cells have to be moved right (and not recipient and date changed).

**Comment by 4miners** [comment]
`Date` column was always next one after `Transaction ID` column. Why we moved it before `Amount` column in this commit? https://github.com/LiskHQ/lisk-explorer/commit/07a0f231cb3b9880b75979e0a85f239e702705f0#diff-17dbc06fb76aa735554ad0b98e347c9b
