### ISSUE TITLE
General UI: approximation symbol

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#646]
### Expected behavior
Approximation symbol (`~`) should be used when an amount is not shown with full precision.
For instance, the `83.25053308` might be shown as `~83.250`, not as `83.250`.

### Actual behavior
There is no indicator that shows that a value is rounded.

**Comment by lsilvs** [comment]
@MichalTuleja  Shouldn't all value that isn't LSK also be shown with the `~`?
I say that because any LSK conversion to any other currency isn't precise.

**Comment by MichalTuleja** [comment]
@lsilvs Yes, let's keep it consistent and use tilde always when the original precision is not shown.
