### ISSUE TITLE
Decimal numbers rounded to full integers

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#648]
The decimal numbers can be shown as an 8-, 4-digits decimal part and with truncated zeros.
This issue adds the full integer display option.

![screen shot 2018-05-16 at 17 27 15](https://user-images.githubusercontent.com/4547510/40128465-f846568c-5931-11e8-9fef-d4193a7d5995.png)

**Comment by lsilvs** [comment]
I would rename it to `Trailing zeros` and `Round to integer` instead.

**Comment by MichalTuleja** [comment]
It's still not decided how the naming should look like.
I've invited @Nazgolze to consider few different naming options.

**Comment by Nazgolze** [comment]
Trailing zeros, that's the term I couldn't remember the other day. It has to be. It has it's own wiki page :)

So something like this:
Show Trailing Zeroes
Hide Trailing Zeroes

That only leaves what to do with "Round to 4" and "Show all 8"...
