### ISSUE TITLE
Review types provided by the Explorer 2.x API

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#706]
It seems that data returned by the Explorer API are different that the 1.x ones. 
While the frontend part didn't change, it can result with many problems like adding two strings `"1"+"1"="11"` and so on.

The aim of this issue is to fix all the problems with types and update the tests accordingly.

**Comment by lsilvs** [comment]
The only occurrence I've identified was already fixed on https://github.com/LiskHQ/lisk-explorer/issues/547

**Comment by MichalTuleja** [comment]
There is at least one incosistency, the field `reward` in this example:

Explorer 1.6
![screen shot 2018-06-21 at 12 48 09](https://user-images.githubusercontent.com/4547510/41714742-a1f7f9fc-7551-11e8-960b-38fafecdbfa0.png)

Explorer 2.1
![screen shot 2018-06-21 at 12 48 20](https://user-images.githubusercontent.com/4547510/41714747-a4189016-7551-11e8-96f1-2b1aa5941942.png)

The aim of this ticket is to cast all values using mappers and to make sure that no matter the Core API changes, the Explorer backend will always send proper data.
