### ISSUE TITLE
Add newsFeed support for Lisk-hub

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-explorer#714]
### Expected behavior
Data service with news feed from twitter, reddit,  academy, github, blog.
For starter data from twitter with LiskHQ would be enough
https://github.com/LiskHQ/lisk-hub/issues/894

Format of newsFeed
```
[
  { timestamp: Data, description: String },
]
```

**Comment by MichalTuleja** [comment]
The API path should be as follows: `service.lisk.io/api/newsfeed/twitter`.
There should be a number of posts limit implemented, set to 50 or 7 days behind.

**Comment by lsilvs** [comment]
@MichalTuleja 
Using `/api/newsfeed/twitter` will require one request for each news feed source.

I suggest using:
`/api/newsFeed?source=all` for all sources
`/api/newsFeed?source=twitter` for only one source
`/api/newsFeed?source=twitter&source=academy` for multiple sources


@michaeltomasik 
I suggest the result format to be:
```
[
  { source: String, timestamp: Data, description: String, url: String },
]
```

**Comment by MichalTuleja** [comment]
I like the idea of using named params. 

I would also suggest adding generic `/api/newsFeed` path that would be equivalent to `/api/newsFeed?source=all` with the limit mentioned earlier. Assuming this will be a standard way the API route is utilized, there's no need to make it complicated.

Also, the API routes should be always lowercase. I know that's not the common practice on that project, but looking forward to the final version of the Service API it'll be good to start with that rule from now on. 

So, we've got two variants that can be used:
`/api/newsfeed` for all sources
`/api/newsfeed?source=all` for all sources
`/api/newsfeed?source=twitter` for only one source
`/api/newsfeed?source=twitter&source=academy` for multiple sources
`/api/newsfeed?source=twitter&source=academy&limit=10&page=2` for multiple sources with pagination

Or:
`/api/newsfeed` for all sources
`/api/newsfeed/twitter` for one source
`/api/newsfeed/twitter,academy` for multiple sources
`/api/newsfeed/twitter,academy/page/2` for multiple sources with pagination

The second one does not support the limit on purpose, it can be still parametrized if needed.

Please use the following output format:
```
[
  { source: String, 
    sourceId: String  // that'd be a Twitter id if available, otherwise null
    timestamp: Data, 
    content: String, 
    url: String }, 
]
```
