### ISSUE TITLE
Revert the breadcrumb spacing to look like 1.6.1

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#718]
The breadcrumb spacing should be visible like the screenshot below:

![screen shot 2018-06-15 at 15 27 50](https://user-images.githubusercontent.com/4547510/41470435-daf61298-70b0-11e8-82d8-5714e854b449.png)

**Comment by lsilvs** [comment]
I believe this is related to this PR https://github.com/LiskHQ/lisk-explorer/pull/692, right?
If so, can you approve the PR before I can revert it, pls?

**Comment by MichalTuleja** [comment]
Not really, #668 does not mention anything about breadcrumbs. That's why #692 should not include any changes to that part. Due to design team not being able to do a review on #668, it is postponed to the `1.7.0` release. The frontend changes in `1.7.0` will include new spacing (#668 and #692) and redesigned currency picker (#721).
