### ISSUE TITLE
Transaction: Voting transaction broken voters links

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#723]
### Expected behavior
A click on a voting delegate name should lead to the delegate page.
There should be an e2e test for that issue. 

### Actual behavior
A click shows the main page because the URL is incomplete.

### Steps to reproduce
https://betanet-explorer.lisk.io/tx/371569150758468336
May occur in the `1.6.x` as well. If it's true, the `1.x` branch should be fixed first, then patch should be implemented in `2.x`.

**Comment by lsilvs** [comment]
`1.6.x` is fine.
https://explorer.lisk.io/tx/2734249697731908390
