### ISSUE TITLE
Temporary information banner

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk-explorer#753]
The Explorer frontend application should support an optional banner containing announcements displayed between the network stats bar and main container.

- [ ] The banner will be shown only if the message is defined in the `config.js` file.
- [ ] The banner should also support hyperlinks in the markdown format.
- [ ] Start of display and expire time should be able to set in the `config.js` file.

Sample message can look like:
```
		<div class="container">
			<div class="panel panel-default" style="background-color: #f1ce48">
				<div class="panel-body">
					Basic panel example
				</div>
			</div>
		</div>
```

**Comment by lsilvs** [comment]
This task is over-engineering a simple requirement imo
