### ISSUE TITLE
Parameter suggestions disappear on click

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk-explorer#759]
### Expected behavior

I would like to be able to click inside parameter suggestion input.

### Actual behavior

When i click on parameter suggestion input it loses focus and if it's empty it disappears if it has a value it sets that value

### Steps to reproduce

navigate: https://testnet-explorer.lisk.io/address/6076671634347365051L
try to add *Sender* and click on the input.

**Comment by lsilvs** [comment]
This search box was implemented using [angular-advanced-searchbox](https://github.com/dnauck/angular-advanced-searchbox) and unfortunately that is its behaviour. The project doesn't seem to be maintained and we have no plans for replacing it for now.
