### ISSUE TITLE
Filters are not always working and overall experience is terrible

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-explorer#773]
Try out a filter like 'Min' and enter the value 1 it will not work.

The overal experience with the filter menu is terrible (tested in Chrome and Firefox). The screenshot is just one example. Please make it more snappy and user-friendly. 
![image](https://user-images.githubusercontent.com/20902562/42882265-0029175c-8a99-11e8-9abe-d28b5780f29e.png)

**Comment by lsilvs** [comment]
The `Min` issue mentioned is related to a core api issue (see https://github.com/LiskHQ/lisk/issues/2358)

Other issues was addressed on this PR https://github.com/LiskHQ/lisk-explorer/pull/806

**Comment by Joo5t** [comment]
Agreed. Just 2 random examples:
![image](https://user-images.githubusercontent.com/20902562/45470915-b69eb380-b72f-11e8-987f-cfe2f34200ca.png)
![image](https://user-images.githubusercontent.com/20902562/45470923-bacad100-b72f-11e8-9758-3a4109002bf2.png)

**Comment by lsilvs** [comment]
As mentioned here https://github.com/LiskHQ/lisk-explorer/issues/773#issuecomment-418104702 the `Min` and other combinations of filters are related to a core api issue (https://github.com/LiskHQ/lisk/issues/2358)

The second one mentioned above was addressed in this PR https://github.com/LiskHQ/lisk-explorer/pull/818. More precisely, in this commit https://github.com/LiskHQ/lisk-explorer/pull/818/commits/d952e3c1cb198ccaf218cb7711410e482f3011d4

I agree it doesn't make sense to close the issue if it's not entirely fixed. I'll reopen and it should be closed when the Core issue is fixed ;)
