### ISSUE TITLE
Explorer breaks on bower deps install

### ISSUE THREAD

**Issue by Phoenix1969** [LiskHQ/lisk-explorer#774]
### Expected behavior 
installation success

### Actual behavior 
i get to npm install and get bower/angular issue ...

```
npm ERR! Linux 2.6.32-042stab127.2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-advanced-searchbox@3.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-advanced-searchbox@3.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-advanced-searchbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-advanced-searchbox
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-advanced-searchbox
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/neo/lisk-explorer/npm-debug.log
```

broken dependency that needs bower when installing (https://github.com/reyraa/angular-advanced-searchbox/blob/master/package.json)

line that causes the problem: https://github.com/reyraa/angular-advanced-searchbox/blob/master/package.json#L44

### Steps to reproduce
simply following git explorer intall directions for ubuntu

**Comment by MichalTuleja** [comment]
Hi @Phoenix1969,
thank you for submitting the issue. I've just tested the `v1.7.2` tag on a fresh Ubuntu 16.x install and the described problem didn't occur. Could you please share more details about your system configuration?

The configuration I've tested:
```
OS: Ubuntu 16.04.5 x64
NodeJS: v8.11.3 (installed via APT)
NPM: 5.6.0
```
-----------------------
Can you try it again applying the following differences to the instruction?
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```
and
```
sudo apt-get install -y python build-essential automake autoconf libtool pkg-config
```
-----------------------
Please notice that the stable code can be found in the tags, not the master/development.
If you want to test the Core 1.0-compatibile branch please use the newest `v2.1.2` tag.
If you want to use your Explorer against the Mainnet please use the `v1.7.2` tag.

**Comment by lsilvs** [comment]
It is a permission issue.

Executing the following commands solves the issue:

```
sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
```

Ref: https://github.com/bower/bower/issues/2262#issuecomment-212601652

It will be added to the README file.
