### ISSUE TITLE
Easy to cheat blockexplorer timestamp

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-explorer#795]
If you create a manual tx on the blockchain and change the timestamp the block explorer shows an incorrect date/time. 
Example:
![image](https://user-images.githubusercontent.com/20902562/44210025-8df1c100-a165-11e8-9123-97c23d7556d5.png)
https://explorer.lisk.io/address/3614574675753534387L

4miners knows how to fix at least the right order the tx are done, but not the timestamp itself: 
![image](https://user-images.githubusercontent.com/20902562/44210068-ba0d4200-a165-11e8-9a0e-5701a41611e0.png)
https://explorer.lisk.4miners.net/account/3614574675753534387L

This tx actually was done about 2018-08-10 9:05:00

**Comment by lsilvs** [comment]
Hi @Joo5t, when you say `This tx actually was done about 2018-08-10 9:05:00` you meant `2018-08-16 9:05:00`, right?

Explorer lists the transactions ordering by timestamp by default and this behaviour is correct.

What you are describing is the fact that the transactions timestamp are set by the sender and it doesn't necessarily reflects the real date and time the transaction was added to a block.

I'm not sure how @4miners implementation is but I would guess he is ordering by the internal ID and not by timestamp.

**Comment by MichalTuleja** [comment]
Hi @Joo5t,

Thank you for pointing this out. 

I would add to the response above that the 4miners Explorer uses sorting by the block height which makes the list sorting correctly, assuming that all transactions are processed in separate blocks. While this technique works fine with the Core 0.9, the newest 1.0 API does not provide sorting by the block height for performance reasons. 

This issue may be addressed in the future versions of Lisk Explorer and there is no possibility to include that improvement in the following Mainnet release for now.
