### ISSUE TITLE
Differentiate transactions in & out

### ISSUE THREAD

**Issue by redsn0w0** [LiskHQ/lisk-explorer#8]
Hi, I think it's better to differentiate the various transactions  **in** / **out** . _IN_ with a green arrow , _OUT_ with a red arrow.

Something like www.blockchain.info  (http://i.imgur.com/zPnX3mt.png)

Thanks.

**Comment by mrv777** [comment]
Guessing this is supposed to be done here:
https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/transaction/tx.html#L19
and here:
https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/transaction/tx.html#L41
but I haven't seen it work.
However, it sounds like you would prefer if the coloring and if statement were done here:
https://github.com/LiskHQ/lisk-explorer/blob/development/public/views/transaction/tx.html#L30
to color the arrow
