### ISSUE TITLE
magnifier clears address field instead of look for typed data

### ISSUE THREAD

**Issue by S3x0r** [LiskHQ/lisk-explorer#809]
### Expected behavior
search for typed data
### Actual behavior
magnifier clears address field instead of look for typed data
### Steps to reproduce
easy
![przechwytywanie](https://user-images.githubusercontent.com/6424893/44998010-811cfc00-afb2-11e8-8f6c-591a9b2aa0aa.PNG)

**Comment by lsilvs** [comment]
Fix here: https://github.com/LiskHQ/lisk-explorer/pull/802

Will be deployed in the following days or week.
