### ISSUE TITLE
Block Explorer filters do not work

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-explorer#819]
My previous ticket is closed without comments and since it still not works I will resubmit it.
Previous ticket = https://github.com/LiskHQ/lisk-explorer/issues/773#issuecomment-420811156

The explorer filters do not work. 2 random examples:
![image](https://user-images.githubusercontent.com/20902562/45471074-42b0db00-b730-11e8-8bae-9cffe06c0cee.png)
![image](https://user-images.githubusercontent.com/20902562/45471084-493f5280-b730-11e8-9f5d-6a3711bbf524.png)

**Comment by Joo5t** [comment]
I was just looking around...maybe this issue is addressed in the current sprint board? Not sure if this is the same thing.
![image](https://user-images.githubusercontent.com/20902562/45471584-d6cf7200-b731-11e8-9ccc-dccbea86d13e.png)

**Comment by MichalTuleja** [comment]
@Joo5t Thank you for submitting this issue. You are right, this issue requires a lot more effort that was initially planned, for this reason it was moved to the following minor release, `2.2.0`.
The issue that you mentioned above is a way to solve the problem.
