### ISSUE TITLE
Make delegate search case-insensitive

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-explorer#822]
Matching results could be improved by also looking for variants in casing in the search query.

**Example:**
Searching for:
 `Korben3 ` gives 0 results
 `korBen3 ` gives 0 results
 `korben ` gives 1 result
 `korben3 ` gives 1 result
 `Elum` gives 0 results
 `elum` gives 1 result

**Note:**

This might be an issue that is present in Lisk core instead of explorer. Since the results are received from the API. In that case, this could be moved to core.

**Screenshot:**

![image](https://user-images.githubusercontent.com/42899281/46915804-3038f400-cfb1-11e8-992e-c6fec6e1c544.png)

**Comment by MichalTuleja** [comment]
This functionality is out of the scope of the current project. It may be considered in the following backend project.
