### ISSUE TITLE
wrong link on delegate name after position change

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk-explorer#824]
### Expected behavior

link on delegate name in the "delegate monitor" page should always point to the correct address.

### Actual behavior

after a couple vote change on testnet, i found out that when the position changed, the links didnt.

for example it was soul on position 101 with the name soul and the link on it pointing to his address

when j0k3r entered and soul got out

j0ker name was listed in position 101 but the link on it was still the link pointing to soul address

### Steps to reproduce

since i did a refresh on the page and the bug dissapered, i guess reading my "actual behavior" description should give you enought informations on what to do to reproduce it. will probably be easier to use a private net to troubleshoot if needed since it need delegates position to change to be able to test

**Comment by youxiberlin** [comment]
We could not reproduce the reported error. 
We investigated and confirmed that the data binding with Angular and backend code were working as we expected. Also, the backend provided the right data.
