### ISSUE TITLE
Empty pages are displayed instead of a redirect to the main page.

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-explorer#827]
### Expected behavior

Upon entering a non existing url /page the user should be redirected to the main page.

### Actual behavior

An empty page is displayed.

### Steps to reproduce

Goto: 
[https://testnet-explorer.lisk.io///](https://testnet-explorer.lisk.io///)

or:
[https://testnet-explorer.lisk.io/address/test/](https://testnet-explorer.lisk.io/address/test/)

### Notes

- It's not user friendly since the user most likely accidentally typed in the incorrect url and should be redirected to the main page instead of given an empty non working page.

- It might also be a small security issue since anyone can create a custom url of lisk explorer and have it indexed by a search engine or shared as 'official'. 

For instance the url:
https://testnet-explorer.lisk.io/address/someverybadwords/ 

Might show up in search engines if it get's indexed.

### Solution

Redirect unknown paths to the main page.

### Screenshots

![image](https://user-images.githubusercontent.com/42899281/48293779-fd373280-e480-11e8-9904-58ada2729de4.png)

![image](https://user-images.githubusercontent.com/42899281/48293713-b8ab9700-e480-11e8-82bf-7df53eb5e7cf.png)

**Comment by MichalTuleja** [comment]
The routing is fixed and shows 404 properly in most of the cases.
Only the triple slash route `///` leads to the blank page.
