### ISSUE TITLE
Delegate/network monitor: enhance the information blocks

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-explorer#868]
Maybe tweakstyle the new GUI a little bit to get a better feeling you are looking at **blocks of information**. Especially for new people the information can be overwelming and difficult to understand what you are looking at.

![image](https://user-images.githubusercontent.com/20902562/50224564-82760700-039e-11e9-88f0-8beb882458d0.png)

Maybe even hide the top information behind a button, like: 
![image](https://user-images.githubusercontent.com/20902562/50224771-04663000-039f-11e9-952b-3a40029a029d.png)

**Comment by punkr0ck** [comment]
I agree with this. Currently the new UI looks a bit unclear / twitchy. The order and allocation should be better.

**Comment by punkr0ck** [comment]
This should be in line, imho.

![grafik](https://user-images.githubusercontent.com/19614645/50340854-e3c3e480-051c-11e9-8df1-0df8ad2c376c.png)

**Comment by MichalTuleja** [comment]
This issue is solved in version `2.2.2`. Issue #875, PR-878 #878.
