### ISSUE TITLE
Add total number of pages to the Transactions list

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-explorer#873]
To give the user an indication where he is in the list of transactions, it would be helpful to display the total number of pages available.

For instance the below 
![image](https://user-images.githubusercontent.com/42899281/50378791-84f48d00-063a-11e9-93b5-090d349ee799.png)

could be changed to:

![image](https://user-images.githubusercontent.com/42899281/50378872-203a3200-063c-11e9-9af7-3f352dbc0741.png)

Another helpful feature would be to allow the user to jump to the first and / or last page, for example like this:

![image](https://user-images.githubusercontent.com/42899281/50378922-faf9f380-063c-11e9-9447-19c34af7ac50.png)

**Comment by MichalTuleja** [comment]
The current backend implementation does not support access to the old blockchain data properly. The issue will be moved to a new project.
