### ISSUE TITLE
Delegate profiles does not show total number of votes

### ISSUE THREAD

**Issue by tomploem** [LiskHQ/lisk-explorer#874]
A delegate profile shows the paginated amount of votes -> "Votes 100". When we press "Load more.."
that amount changes to "Votes 200". 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/12698415/50383354-40a4d380-06b2-11e9-8a81-e70ecf2b0331.png">

The previous behavior was that the total amount of votes was showed, for example the profile [endro](https://explorer.lisk.io/address/9096358076943957197L) has 519 votes. Now you need to press 6 times on "Load more" to know that number.

**Comment by Korben3** [comment]
In the following line `<h3>Votes <small>{{vm.address.votes.**length**}}</small></h3>` length might need to be replaced with count.

https://github.com/LiskHQ/lisk-explorer/blob/2.2.0/src/components/address/address.html#L120
