### ISSUE TITLE
Unable to find numerical named delegates

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-explorer#898]
### Expected behavior

Searching for delegates which usernames consist of only numbers should result in the delegate being found and displayed.

### Actual behavior

Instead of the delegate, explorer jumps to the block page showing a block which height corresponds with the numerical value being searched.

### Steps to reproduce

For testing purpose, I created a delegate called **9** on testnet.

1. Goto testnet-explorer.lisk.io and search for 9.
2. Delegate **9** can not be found instead explorer jumps to https://testnet-explorer.lisk.io/block/14903071205872749707
with block height 9, see screenshot.

![image](https://user-images.githubusercontent.com/42899281/54865999-027d8580-4d6f-11e9-80fc-eb024d00c3c5.png)

Link to delegate 9: https://testnet-explorer.lisk.io/address/3407628475523165972L

![image](https://user-images.githubusercontent.com/42899281/54866104-589ef880-4d70-11e9-93bd-662a7c877966.png)

The same applies to delegate names like 007, 31337, etc.

This means potentially 100000000000000000000 delegates/usernames are unable to be shown in the explorer. (max 20 character names are allowed).

**Comment by MichalTuleja** [comment]
@Korben3 Thank you for submitting the issue. The described problem is solved on `testnet` and is on its way to be applied on `mainnet` Explorer.
