### ISSUE TITLE
Address length < 16

### ISSUE THREAD

**Issue by AxlSaddek** [LiskHQ/lisk-explorer#9]
Hi,
Address with a length < 16 are valid but cannot be searched.
eg: 202243225L

Thanks.

**Comment by fix** [comment]
Hi @AxlSaddek thanks for reporting actually this even does not work https://explorer.lisk.io/address/202243225L

**Comment by simonmorgenthaler** [comment]
It just expired:
[inf] 2017-01-08 17:09:16 | Expired transaction: 14467342019343228805 received at: Sun, 08 Jan 2017 14:08:56 GMT
