### ISSUE TITLE
Missing recipient in custom transaction

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk-explorer#923]
### Expected behavior
Explorer should work with sdk and custom tx

### Actual behavior
It does not
<img width="577" alt="Screenshot_2019-09-20_at_23 57 04" src="https://user-images.githubusercontent.com/9548618/65378328-80d7c780-dcbf-11e9-96a3-78a6acf9745f.png">
<img width="1152" alt="Screenshot_2019-09-20_at_23 56 59" src="https://user-images.githubusercontent.com/9548618/65378329-82a18b00-dcbf-11e9-82a5-d78fbb343364.png">
Response from lisk-sdk
```
{
	"meta": {
		"offset": 0,
		"limit": 10,
		"count": 1
	},
	"data": [{
		"id": "16984676768532700737",
		"height": 774,
		"blockId": "4077074909819091464",
		"type": 11,
		"timestamp": 10295682,
		"senderPublicKey": "c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f",
		"recipientPublicKey": "addb0e15a44b0fdc6ff291be28d8c98f5551d0cd9218d749e30ddb87c6e31ca9",
		"senderId": "16313739661670634666L",
		"recipientId": "10881167371402274308L",
		"amount": "1000000000000",
		"fee": "10000000",
		"signature": "b9c072d0667a9219615f8abb1226812532fe3a5e830f34d8b724baa5088f8db27754d82e958f570988d2576e0d90c16dde5a0bc89696c7b0f3f325ffbb855409",
		"signatures": [],
		"asset": {},
		"confirmations": 16241
	}],
	"links": {}
}

```
### Steps to reproduce
Run cashback example and query custom tx.

**Comment by MichalTuleja** [comment]
Lisk Explorer is designed to work with official `mainnet` and `testnet` networks only.
This feature will not be planned in the future releases of Explorer.
