### ISSUE TITLE
Update Chat Link on Explorer from RocketChat to Discord

### ISSUE THREAD

**Issue by Nimbus76** [LiskHQ/lisk-explorer#924]
Explorer still shows RocketChat link at bottom of page. This should be updated to Discord icon and link.

**Comment by MichalTuleja** [comment]
The layout on the bottom should be aligned with the current [lisk.io](https://lisk.io/) layout.

Please update the links, consider the picture below for a reference.

![image (3)](https://user-images.githubusercontent.com/4547510/68466973-b146d700-0215-11ea-8e7d-a5d42bd8f419.png)

**Comment by slaweet** [comment]
The original goal of this ticket was already solved in https://github.com/LiskHQ/lisk-explorer/pull/921/files, though not released, yet.

@MichalTuleja which of the following do you mean should be implemented to align the layout with website:
1. Sizes and spacing of icons
2. Order of icons
3. Removing icons that are extra on Explorer, that is Telegram, Instagram, Medium.
4. Add "Follow Lisk on:" text
