### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-explorer#929]
I suggest to change the Rocketchat-logo to Discord logo and also remove Telegram completely as it is not official anymore and no HQ-members write there.

![grafik](https://user-images.githubusercontent.com/19614645/68978008-f6f93600-07f9-11ea-99ff-2abb1a9038c3.png)

**Comment by slaweet** [comment]
Thank you for the report, @punkr0ck.
I'll close this as a duplicate to https://github.com/LiskHQ/lisk-explorer/issues/924 
The issue was already fixed in https://github.com/LiskHQ/lisk-explorer/pull/928 but not released, yet.
