### ISSUE TITLE
Explorer fall in loop after failed request location from freegeoip

### ISSUE THREAD

**Issue by biolypl** [LiskHQ/lisk-explorer#99]
Seems that 1.1.0 explorer fall in loop after some failed freegeoip request's. This bug costs endless server resources, logs: http://pastebin.com/GjfdqnL4

**Comment by 4miners** [comment]
Thank you for reporting it, will investigate.

**Comment by 4miners** [comment]
@biolypl I investigated it, but cannot reproduce. Also I never had this issue of any of my running explorers. If you still notice that issue - please reopen and add log that include periods just before and short after that issue.
